server:
  port: 8080
spring:
  application:
    name: "cleanArchTest"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
app:
  name: "NU0197001_VinculacionTransversalFront_MR"
  component: "ms_customer_acquisition"
  perfil: "local"
aws:
  dynamodb:
    endpoint: http://dynamodb.us-east-1.amazonaws.com
    prefix: nu0034001-vinculacion-transversal-dev-dy-
    region:
    tableName: "nu0197001-front-vinculacion-transversal-dev-dy-catalogs"
    accessKeyId: ""
    secretAccessKey: "+ZXpqyMM"
    secret:
      region:
      name: